export const cards = [
    {
        color: "Karo",
        number: 2,
        value: 2
    }, {
        color: "Karo",
        number: 3,
        value: 3
    }, {
        color: "Karo",
        number: 4,
        value: 4
    }, {
        color: "Karo",
        number: 5,
        value: 5
    }, {
        color: "Karo",
        number: 6,
        value: 6
    }, {
        color: "Karo",
        number: 7,
        value: 7
    }, {
        color: "Karo",
        number: 8,
        value: 8
    }, {
        color: "Karo",
        number: 9,
        value: 9
    }, {
        color: "Karo",
        number: 10,
        value: 10
    }, {
        color: "Karo",
        number: "Jack",
        value: 11
    }, {
        color: "Karo",
        number: "Queen",
        value: 12
    }, {
        color: "Karo",
        number: "King",
        value: 13
    }, {
        color: "Karo",
        number: "Ace",
        value: 14
    }, {
        color: "Kreuz",
        number: 2,
        value: 2
    }, {
        color: "Kreuz",
        number: 3,
        value: 3
    }, {
        color: "Kreuz",
        number: 4,
        value: 4
    }, {
        color: "Kreuz",
        number: 5,
        value: 5
    }, {
        color: "Kreuz",
        number: 6,
        value: 6
    }, {
        color: "Kreuz",
        number: 7,
        value: 7
    }, {
        color: "Kreuz",
        number: 8,
        value: 8
    }, {
        color: "Kreuz",
        number: 9,
        value: 9
    }, {
        color: "Kreuz",
        number: 10,
        value: 10
    }, {
        color: "Kreuz",
        number: "Jack",
        value: 11
    }, {
        color: "Kreuz",
        number: "Queen",
        value: 12
    }, {
        color: "Kreuz",
        number: "King",
        value: 13
    }, {
        color: "Kreuz",
        number: "Ace",
        value: 14
    }, {
        color: "Pik",
        number: 2,
        value: 2
    }, {
        color: "Pik",
        number: 3,
        value: 3
    }, {
        color: "Pik",
        number: 4,
        value: 4
    }, {
        color: "Pik",
        number: 5,
        value: 5
    }, {
        color: "Pik",
        number: 6,
        value: 6
    }, {
        color: "Pik",
        number: 7,
        value: 7
    }, {
        color: "Pik",
        number: 8,
        value: 8
    }, {
        color: "Pik",
        number: 9,
        value: 9
    }, {
        color: "Pik",
        number: 10,
        value: 10
    }, {
        color: "Pik",
        number: "Jack",
        value: 11
    }, {
        color: "Pik",
        number: "Queen",
        value: 12
    }, {
        color: "Pik",
        number: "King",
        value: 13
    }, {

        color: "Pik",
        number: "Ace",
        value: 14
    }, {
        color: "Herz",
        number: 2,
        value: 2
    }, {
        color: "Herz",
        number: 3,
        value: 3
    }, {
        color: "Herz",
        number: 4,
        value: 4
    }, {
        color: "Herz",
        number: 5,
        value: 5
    }, {
        color: "Herz",
        number: 6,
        value: 6
    }, {
        color: "Herz",
        number: 7,
        value: 7
    }, {
        color: "Herz",
        number: 8,
        value: 8
    }, {
        color: "Herz",
        number: 9,
        value: 9
    }, {
        color: "Herz",
        number: 10,
        value: 10
    }, {
        color: "Herz",
        number: "Jack",
        value: 11
    }, {
        color: "Herz",
        number: "Queen",
        value: 12
    }, {
        color: "Herz",
        number: "King",
        value: 13
    }, {
        color: "Herz",
        number: "Ace",
        value: 14
    }
]