export const karten = [
    {
        farbe: "Karo",
        wert: 2,
        numWert: 2
    }, {
        farbe: "Karo",
        wert: 3,
        numWert: 3
    }, {
        farbe: "Karo",
        wert: 4,
        numWert: 4
    }, {
        farbe: "Karo",
        wert: 5,
        numWert: 5
    }, {
        farbe: "Karo",
        wert: 6,
        numWert: 6
    }, {
        farbe: "Karo",
        wert: 7,
        numWert: 7
    }, {
        farbe: "Karo",
        wert: 8,
        numWert: 8
    }, {
        farbe: "Karo",
        wert: 9,
        numWert: 9
    }, {
        farbe: "Karo",
        wert: 10,
        numWert: 10
    }, {
        farbe: "Karo",
        wert: "Bube",
        numWert: 11
    }, {
        farbe: "Karo",
        wert: "Dame",
        numWert: 12
    }, {
        farbe: "Karo",
        wert: "Koenig",
        numWert: 13
    }, {
        farbe: "Karo",
        wert: "Ass",
        numWert: 14
    }, {
        farbe: "Kreuz",
        wert: 2,
        numWert: 2
    }, {
        farbe: "Kreuz",
        wert: 3,
        numWert: 3
    }, {
        farbe: "Kreuz",
        wert: 4,
        numWert: 4
    }, {
        farbe: "Kreuz",
        wert: 5,
        numWert: 5
    }, {
        farbe: "Kreuz",
        wert: 6,
        numWert: 6
    }, {
        farbe: "Kreuz",
        wert: 7,
        numWert: 7
    }, {
        farbe: "Kreuz",
        wert: 8,
        numWert: 8
    }, {
        farbe: "Kreuz",
        wert: 9,
        numWert: 9
    }, {
        farbe: "Kreuz",
        wert: 10,
        numWert: 10
    }, {
        farbe: "Kreuz",
        wert: "Bube",
        numWert: 11
    }, {
        farbe: "Kreuz",
        wert: "Dame",
        numWert: 12
    }, {
        farbe: "Kreuz",
        wert: "Koenig",
        numWert: 13
    }, {
        farbe: "Kreuz",
        wert: "Ass",
        numWert: 14
    }, {
        farbe: "Pik",
        wert: 2,
        numWert: 2
    }, {
        farbe: "Pik",
        wert: 3,
        numWert: 3
    }, {
        farbe: "Pik",
        wert: 4,
        numWert: 4
    }, {
        farbe: "Pik",
        wert: 5,
        numWert: 5
    }, {
        farbe: "Pik",
        wert: 6,
        numWert: 6
    }, {
        farbe: "Pik",
        wert: 7,
        numWert: 7
    }, {
        farbe: "Pik",
        wert: 8,
        numWert: 8
    }, {
        farbe: "Pik",
        wert: 9,
        numWert: 9
    }, {
        farbe: "Pik",
        wert: 10,
        numWert: 10
    }, {
        farbe: "Pik",
        wert: "Bube",
        numWert: 11
    }, {
        farbe: "Pik",
        wert: "Dame",
        numWert: 12
    }, {
        farbe: "Pik",
        wert: "Koenig",
        numWert: 13
    }, {

        farbe: "Pik",
        wert: "Ass",
        numWert: 14
    }, {
        farbe: "Herz",
        wert: 2,
        numWert: 2
    }, {
        farbe: "Herz",
        wert: 3,
        numWert: 3
    }, {
        farbe: "Herz",
        wert: 4,
        numWert: 4
    }, {
        farbe: "Herz",
        wert: 5,
        numWert: 5
    }, {
        farbe: "Herz",
        wert: 6,
        numWert: 6
    }, {
        farbe: "Herz",
        wert: 7,
        numWert: 7
    }, {
        farbe: "Herz",
        wert: 8,
        numWert: 8
    }, {
        farbe: "Herz",
        wert: 9,
        numWert: 9
    }, {
        farbe: "Herz",
        wert: 10,
        numWert: 10
    }, {
        farbe: "Herz",
        wert: "Bube",
        numWert: 11
    }, {
        farbe: "Herz",
        wert: "Dame",
        numWert: 12
    }, {
        farbe: "Herz",
        wert: "Koenig",
        numWert: 13
    }, {
        farbe: "Herz",
        wert: "Ass",
        numWert: 14
    }
]